name: Dependency Review

on:
  pull_request:
    paths:
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail on high/critical vulnerabilities
          fail-on-severity: moderate
          # Allow licenses commonly used in Python ecosystem
          allow-licenses: MIT, Apache-2.0, BSD-3-Clause, BSD-2-Clause, ISC, MPL-2.0
          # Comment on PR with results
          comment-summary-in-pr: true
