name: Security Scorecard

on:
  branch_protection_rule:
  schedule:
    # Run weekly on Sundays at 2 AM (Brazil time: 11 PM Saturday)
    - cron: '0 5 * * 0'
  push:
    branches: [ main ]
  workflow_dispatch:

permissions: read-all

jobs:
  analysis:
    name: Security Scorecard Analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      # Needed to publish results and get a badge.
      id-token: write
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          # Public repository to enable badges
          publish_results: true

      # Upload the results to GitHub's code scanning dashboard
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
